# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e1bccd22719631a62668103149cb9509"
name = "Shopfunnel"
application_url = "https://shopfunnel.com/api/shopify/authorize"
embedded = false

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://shopfunnel.com/api/shopify/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_products,write_pixels"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = ["https://shopfunnel.com/api/shopify/callback"]
