# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c91c3d67914ad6bd37da12733c00e54f"
name = "Shopfunnel Dev"
application_url = "https://dev.shopfunnel.com/api/shopify/authorize"
embedded = false

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://dev.shopfunnel.com/api/shopify/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_products,write_pixels"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = ["https://dev.shopfunnel.com/api/shopify/callback"]
